-- Create email_notifications table to track sent emails
CREATE TABLE IF NOT EXISTS email_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  recipient TEXT NOT NULL,
  subject TEXT NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT NOT NULL,
  message_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add index for faster lookups by order_id
CREATE INDEX IF NOT EXISTS idx_email_notifications_order_id ON email_notifications(order_id);

-- Enable RLS
ALTER TABLE email_notifications ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow anonymous read access to email_notifications"
  ON email_notifications FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Allow anonymous insert access to email_notifications"
  ON email_notifications FOR INSERT
  TO anon
  WITH CHECK (true);
